let stockProductos = [
    {id: 1, nombre: "Spy X Family",  cantidad: 1,  precio: 1200, Genero: "Accion,Comedia", img: '../imgmangas/spyxfamilimanga.jpg'},
    {id: 3, nombre: "Blue Lock",  cantidad: 1,  precio: 1200, Genero: "Deporte", img: '../imgmangas/bluelockmanga.jpg'},
    {id: 4, nombre: "Darlign In FranXx",  cantidad: 1,  precio: 1400, Genero: "Romance,Accion", img: '../imgmangas/zerotwomanga.jfif'},
    {id: 5, nombre: "Wotakoi",  cantidad: 1,  precio: 1200, Genero: "Romance,Comedia", img: '../imgmangas/wotakoimanga.jpg'},
    {id: 6, nombre: "Horimiya",  cantidad: 1,  precio: 950, Genero: "Comedia,Romance", img: '../imgmangas/horimiyamang.jpg'},
    {id: 7, nombre: "Chainsaw-Man",  cantidad: 1,  precio: 1200, Genero: "Accion,SobreNatural", img: '../imgmangas/portadachainsaw.jpg'},
    {id: 8, nombre: "One Piece",  cantidad: 1,  precio: 950, Genero: "Isekai", img: '../imgmangas/portadaonepiece.jpg'},
    {id: 9, nombre: "Bleach",  cantidad: 1,  precio: 1200, Genero: "Accion", img: '../imgmangas/portadableach.jpg'},
    {id: 10, nombre: "Jujutsu Kaisen 0",  cantidad: 1,  precio: 1200, Genero: "Accion,SobreNatural", img: '../imgmangas/portadajujutsu0.jpg'},
    {id: 11, nombre: "Jujutsu Kaisen 1", cantidad: 1, precio: 800, Genero: "Accion,SobreNatural", img: '../imgmangas/portadajujutsu1.jpg'},
    {id: 12, nombre: "Sword Art Online",  cantidad: 1,  precio: 850, Genero: "Isekai,Romance", img: '../imgmangas/portadasaomanga.jpg'},
    {id: 13, nombre: "Banana Fish",  cantidad: 1,  precio: 1900, Genero: "Accion,Romance", img: '../imgmangas/portadabananafish.jpg'},
    {id: 14, nombre: "Given",  cantidad: 1,  precio: 1400, Genero: "Romance", img: '../imgmangas/portadagiven.jpg'},
    {id: 15, nombre: "Berserk",  cantidad: 1,  precio: 1200, Genero: "Accion", img: '../imgmangas/portadaberserk.jpg'},
    {id: 16, nombre: "Fire Force",  cantidad: 1,  precio: 950, Genero: "Accion,SobreNatural", img: '../imgmangas/fireforcemanga.jpg'},
    {id: 17, nombre: "Hanako-Kun",  cantidad: 1,  precio: 1200, Genero: "SobreNatural,Romance", img: '../imgmangas/hanakomanga.jpg'},
    {id: 18, nombre: "Call Of The Night",  cantidad: 1,  precio: 1200, Genero: "Romance,Comedia", img: '../imgmangas/callofthenightmanga.jpg '},
    {id: 19, nombre: "Ao Haru Ride",  cantidad: 1,  precio: 800, Genero: "Romance", img: '../imgmangas/portadaaoharuride.jpg'},
    {id: 20, nombre: "Devour Your Heart",  cantidad: 1,  precio: 800, Genero: "Romance", img: '../imgmangas/portadadtc.jpg'},
    {id: 21, nombre: "Haikyuu",  cantidad: 1,  precio: 1200, Genero: "Deporte", img: '../imgmangas/portadahaikyuu.jpg'},
    {id: 22, nombre: "Demon Slayer",  cantidad: 1,  precio: 1200, Genero: "Accion,Isekai", img: '../imgmangas/portadakny.jpg'},
    {id: 23, nombre: "Bunny Girl Senpai",  cantidad: 1,  precio: 850, Genero: "Accion,Romance,Isekai", img: '../imgmangas/portada86.jpg'},
    {id: 24, nombre: "Bunny Girl Senpai",  cantidad: 1,  precio: 850, Genero: "Romance,SobreNatural", img: '../imgmangas/portadabgs.jpg'},
    {id: 25, nombre: "Atack Of Titans",  cantidad: 1,  precio: 1200, Genero: "Accion,Isekai", img: '../imgmangas/portadaaot.jpg'},
]